export const vocabularyData = {
  verbs: [
    {
      word: "emerged",
      meaning: "Came out or appeared",
      impression: "Surprise, change",
      examples: [
        "A butterfly emerged from its cocoon, wings glistening.",
        "The truth finally emerged after months of investigation.",
      ],
      hints: ["Something appearing or coming out", "Often shows a revelation or transformation"],
      swapFrom: "came out",
      sentenceTemplate: "The butterfly came out from its cocoon.",
      sentenceAnswer: "The butterfly emerged from its cocoon.",
    },
    {
      word: "swarmed",
      meaning: "Moved in a large, busy group",
      impression: "Chaos, activity",
      examples: ["Tourists swarmed the beach on the sunny weekend.", "Bees swarmed around the fallen ice cream cone."],
      hints: ["Many moving together in a busy way", "Creates feeling of crowded chaos"],
      swapFrom: "moved in a big group",
      sentenceTemplate: "The tourists moved in a big group to the beach.",
      sentenceAnswer: "The tourists swarmed to the beach.",
    },
    {
      word: "devoured",
      meaning: "Ate greedily or hungrily",
      impression: "Hunger, desire",
      examples: [
        "The hungry child devoured the entire pizza.",
        "She devoured the book in a single sitting, eager for more.",
      ],
      hints: ["Think of eating very quickly and eagerly", "Shows strong hunger or intense consumption"],
      swapFrom: "ate quickly",
      sentenceTemplate: "He ate quickly after the long hike.",
      sentenceAnswer: "He devoured his meal after the long hike.",
    },
    {
      word: "wandered",
      meaning: "Walked slowly without a clear destination",
      impression: "Aimlessness, exploration",
      examples: [
        "She wandered through the forest, enjoying the peaceful sounds.",
        "He wandered the streets, lost in thought.",
      ],
      hints: ["Walking without a specific goal", "Often suggests being lost or exploring"],
      swapFrom: "walked around",
      sentenceTemplate: "She walked around through the forest.",
      sentenceAnswer: "She wandered through the forest.",
    },
    {
      word: "whispered",
      meaning: "Spoke very softly or quietly",
      impression: "Secrecy, intimacy",
      examples: [
        "She whispered the secret into her friend's ear.",
        "The wind whispered through the trees.",
      ],
      hints: ["Speaking very quietly", "Can suggest secrets or gentle sounds"],
      swapFrom: "said quietly",
      sentenceTemplate: "She said quietly into her friend's ear.",
      sentenceAnswer: "She whispered into her friend's ear.",
    },
    {
      word: "trembled",
      meaning: "Shook slightly, usually from fear or cold",
      impression: "Fear, weakness",
      examples: [
        "Her hands trembled as she opened the letter.",
        "The small dog trembled in the thunderstorm.",
      ],
      hints: ["Shaking from emotion or temperature", "Shows vulnerability or fear"],
      swapFrom: "shook",
      sentenceTemplate: "Her hands shook as she opened the letter.",
      sentenceAnswer: "Her hands trembled as she opened the letter.",
    },
    {
      word: "glared",
      meaning: "Stared angrily",
      impression: "Anger, hostility",
      examples: [
        "She glared at the rude customer.",
        "The teacher glared at the students talking during the test.",
      ],
      hints: ["Looking at someone with anger", "A fierce, unfriendly stare"],
      swapFrom: "looked angrily",
      sentenceTemplate: "She looked angrily at the rude customer.",
      sentenceAnswer: "She glared at the rude customer.",
    },
    {
      word: "muttered",
      meaning: "Spoke in a low, unclear voice, often complaining",
      impression: "Annoyance, discontent",
      examples: [
        "He muttered under his breath about the long wait.",
        "She muttered something about unfairness as she left.",
      ],
      hints: ["Speaking quietly and unclearly", "Often shows irritation or complaint"],
      swapFrom: "said quietly",
      sentenceTemplate: "He said quietly under his breath about the long wait.",
      sentenceAnswer: "He muttered under his breath about the long wait.",
    },
  ],
  adjectives: [
    {
      word: "desolate",
      meaning: "Empty, without life",
      impression: "Loneliness, abandonment",
      examples: [
        "The desolate playground stood empty in the moonlight.",
        "He walked through the desolate streets, feeling utterly alone.",
      ],
      hints: ["Describe an empty, lonely place", "Creates a sad, abandoned feeling"],
      swapFrom: "empty and sad",
      sentenceTemplate: "The place looked empty and sad.",
      sentenceAnswer: "The place looked desolate.",
    },
    {
      word: "sumptuous",
      meaning: "Rich, luxurious, and impressive",
      impression: "Pleasure, indulgence",
      examples: [
        "The sumptuous feast made everyone's mouth water.",
        "She admired the sumptuous velvet curtains in the theater.",
      ],
      hints: ["Describes something very fancy and expensive", "Makes you think of luxury and wealth"],
      swapFrom: "very fancy and rich",
      sentenceTemplate: "The food was very fancy and rich.",
      sentenceAnswer: "The food was sumptuous.",
    },
    {
      word: "sinister",
      meaning: "Scary and suggesting something bad will happen",
      impression: "Evil, threat",
      examples: [
        "A sinister smile crept across his face as he stepped into the shadows.",
        "The sinister figure watched from behind the tree.",
      ],
      hints: ["Describes someone who seems evil or threatening", "Creates fear and suspicion"],
      swapFrom: "scary and bad",
      sentenceTemplate: "The man had a scary and bad smile.",
      sentenceAnswer: "The man had a sinister smile.",
    },
    {
      word: "cruel",
      meaning: "Enjoying hurting or upsetting others",
      impression: "Meanness, harm",
      examples: [
        "The cruel bully laughed at the smaller child's tears.",
        "His cruel words left her feeling deeply hurt.",
      ],
      hints: ["Someone who enjoys causing pain or distress", "Deliberately unkind and hurtful"],
      swapFrom: "mean and hurtful",
      sentenceTemplate: "His mean and hurtful words left her feeling deeply hurt.",
      sentenceAnswer: "His cruel words left her feeling deeply hurt.",
    },
    {
      word: "compassionate",
      meaning: "Showing care and concern for others",
      impression: "Kindness, empathy",
      examples: [
        "The compassionate nurse held the patient's hand gently.",
        "Her compassionate nature made everyone feel welcomed.",
      ],
      hints: ["Someone who cares deeply about others", "Shows kindness and understanding"],
      swapFrom: "very nice and loving",
      sentenceTemplate: "The nurse was very nice and loving.",
      sentenceAnswer: "The nurse was compassionate.",
    },
    {
      word: "hostile",
      meaning: "Angry and unfriendly",
      impression: "Aggression, unfriendliness",
      examples: [
        "The hostile crowd shouted angrily at the speaker.",
        "His hostile attitude made everyone uncomfortable.",
      ],
      hints: ["Someone who is angry and unwelcoming", "Unfriendly and aggressive behavior"],
      swapFrom: "angry and unfriendly",
      sentenceTemplate: "The crowd was angry and unfriendly.",
      sentenceAnswer: "The crowd was hostile.",
    },
    {
      word: "gentle",
      meaning: "Soft, calm, and caring",
      impression: "Kindness, softness",
      examples: [
        "The gentle giant carefully picked up the injured bird.",
        "Her gentle voice calmed the frightened child.",
      ],
      hints: ["Someone who is soft and careful", "Never harsh or rough"],
      swapFrom: "nice and soft",
      sentenceTemplate: "The giant was nice and soft.",
      sentenceAnswer: "The giant was gentle.",
    },
    {
      word: "fierce",
      meaning: "Strong, angry, or powerful",
      impression: "Intensity, power",
      examples: [
        "The fierce warrior defended the castle bravely.",
        "She gave him a fierce look that made him step back.",
      ],
      hints: ["Someone very intense and powerful", "Strong emotions, often anger or determination"],
      swapFrom: "very angry and strong",
      sentenceTemplate: "The warrior was very angry and strong.",
      sentenceAnswer: "The warrior was fierce.",
    },
  ],
  nouns: [
    {
      word: "refuge",
      meaning: "A safe place",
      impression: "Safety, comfort",
      examples: [
        "The library became her refuge from the chaos outside.",
        "They found refuge in the warm cabin during the storm.",
      ],
      hints: ["Think of somewhere safe to hide", "A place of comfort and protection"],
      swapFrom: "safe place",
      sentenceTemplate: "The cabin was a safe place during the storm.",
      sentenceAnswer: "The cabin was a refuge during the storm.",
    },
    {
      word: "chaos",
      meaning: "Complete disorder and confusion",
      impression: "Disorder, confusion",
      examples: [
        "The classroom descended into chaos when the teacher left.",
        "After the earthquake, the city was in complete chaos.",
      ],
      hints: ["Total disorder and mess", "Everything out of control"],
      swapFrom: "complete mess",
      sentenceTemplate: "The classroom became a complete mess when the teacher left.",
      sentenceAnswer: "The classroom descended into chaos when the teacher left.",
    },
    {
      word: "tranquility",
      meaning: "The quality of being calm and peaceful",
      impression: "Peace, calmness",
      examples: [
        "The garden offered a sense of tranquility after the busy day.",
        "She sought tranquility in the quiet mountain retreat.",
      ],
      hints: ["A state of peace and calm", "Absence of noise or disturbance"],
      swapFrom: "peaceful feeling",
      sentenceTemplate: "The garden offered a peaceful feeling after the busy day.",
      sentenceAnswer: "The garden offered tranquility after the busy day.",
    },
    {
      word: "turmoil",
      meaning: "A state of great disturbance or confusion",
      impression: "Distress, upheaval",
      examples: [
        "The country was in political turmoil.",
        "Her mind was in turmoil after hearing the shocking news.",
      ],
      hints: ["Extreme confusion or upset", "Internal or external disturbance"],
      swapFrom: "great confusion",
      sentenceTemplate: "The country was in great confusion.",
      sentenceAnswer: "The country was in turmoil.",
    },
    {
      word: "glimpse",
      meaning: "A brief or partial view",
      impression: "Fleeting, brief",
      examples: [
        "She caught a glimpse of the celebrity through the crowd.",
        "The curtains opened to give a glimpse of the stage.",
      ],
      hints: ["A quick look at something", "Only seeing something briefly"],
      swapFrom: "quick look",
      sentenceTemplate: "She caught a quick look of the celebrity through the crowd.",
      sentenceAnswer: "She caught a glimpse of the celebrity through the crowd.",
    },
    {
      word: "abundance",
      meaning: "A very large quantity of something",
      impression: "Plenty, richness",
      examples: [
        "The garden had an abundance of colorful flowers.",
        "There was an abundance of food at the celebration.",
      ],
      hints: ["Having more than enough", "A plentiful supply"],
      swapFrom: "lots of",
      sentenceTemplate: "The garden had lots of colorful flowers.",
      sentenceAnswer: "The garden had an abundance of colorful flowers.",
    },
  ],
  adverbs: [
    {
      word: "frantically",
      meaning: "In a way that is fast and shows fear or worry",
      impression: "Panic, urgency",
      examples: [
        "She frantically searched through her bag for the missing keys.",
        "The crowd frantically ran through the station.",
      ],
      hints: ["Think about someone in a rush and worried", "Use it to show panic or urgent movement"],
      swapFrom: "quickly and nervously",
      sentenceTemplate: "She ran quickly and nervously down the hallway.",
      sentenceAnswer: "She ran frantically down the hallway.",
    },
    {
      word: "cautiously",
      meaning: "In a careful way, avoiding danger or risk",
      impression: "Care, wariness",
      examples: [
        "She cautiously approached the sleeping dog.",
        "He cautiously opened the old creaky door.",
      ],
      hints: ["Moving or acting carefully", "Being alert to potential danger"],
      swapFrom: "very carefully",
      sentenceTemplate: "She very carefully approached the sleeping dog.",
      sentenceAnswer: "She cautiously approached the sleeping dog.",
    },
    {
      word: "reluctantly",
      meaning: "In an unwilling or hesitant way",
      impression: "Unwillingness, hesitation",
      examples: [
        "He reluctantly agreed to help with the difficult task.",
        "She reluctantly said goodbye to her friends.",
      ],
      hints: ["Doing something you don't want to do", "Showing hesitation or unwillingness"],
      swapFrom: "unwillingly",
      sentenceTemplate: "He unwillingly agreed to help with the difficult task.",
      sentenceAnswer: "He reluctantly agreed to help with the difficult task.",
    },
    {
      word: "anxiously",
      meaning: "In a worried or nervous way",
      impression: "Worry, nervousness",
      examples: [
        "She anxiously waited for the test results.",
        "The dog anxiously paced by the door, waiting for its owner.",
      ],
      hints: ["Feeling worried or nervous", "Showing concern or unease"],
      swapFrom: "nervously",
      sentenceTemplate: "She nervously waited for the test results.",
      sentenceAnswer: "She anxiously waited for the test results.",
    },
    {
      word: "deliberately",
      meaning: "On purpose; intentionally",
      impression: "Intention, purpose",
      examples: [
        "He deliberately ignored her calls.",
        "She deliberately chose the hardest path to challenge herself.",
      ],
      hints: ["Doing something on purpose", "Not by accident"],
      swapFrom: "on purpose",
      sentenceTemplate: "He on purpose ignored her calls.",
      sentenceAnswer: "He deliberately ignored her calls.",
    },
    {
      word: "gracefully",
      meaning: "In a smooth, elegant way",
      impression: "Elegance, beauty",
      examples: [
        "The dancer moved gracefully across the stage.",
        "The swan glided gracefully on the lake.",
      ],
      hints: ["Moving smoothly and beautifully", "With elegance and poise"],
      swapFrom: "smoothly and beautifully",
      sentenceTemplate: "The dancer moved smoothly and beautifully across the stage.",
      sentenceAnswer: "The dancer moved gracefully across the stage.",
    },
  ],
}

export type Stage = 1 | 2 | 3 | 4 | 5
export type VocabType = "verbs" | "adjectives" | "nouns" | "adverbs"

export interface VocabularyItem {
  word: string
  meaning: string
  impression: string
  examples: string[]
  hints?: string[] // Hints are optional now
  swapFrom?: string // New property for word swap stage
  sentenceTemplate?: string
  sentenceAnswer?: string
}
