export const vocabularyData = {
  descriptive: [
    {
      word: "frantically",
      meaning: "A way of doing something quickly and nervously",
      impression: "Panic, urgency",
      examples: [
        "The crowd frantically ran through the station, panic rising in every breath.",
        "She frantically searched through her bag for the missing keys.",
      ],
      hints: ["Think about someone in a rush and worried", "Use it to show panic or urgent movement"],
      swapFrom: "quickly and nervously",
      sentenceTemplate: "She ran quickly and nervously down the hallway.",
      sentenceAnswer: "She ran frantically down the hallway.",
    },
    {
      word: "desolate",
      meaning: "Empty, without life",
      impression: "Loneliness, abandonment",
      examples: [
        "The desolate playground stood empty in the moonlight.",
        "He walked through the desolate streets, feeling utterly alone.",
      ],
      hints: ["Describe an empty, lonely place", "Creates a sad, abandoned feeling"],
      swapFrom: "empty and sad",
      sentenceTemplate: "The place looked empty and sad.",
      sentenceAnswer: "The place looked desolate.",
    },
    {
      word: "refuge",
      meaning: "A safe place",
      impression: "Safety, comfort",
      examples: [
        "The library became her refuge from the chaos outside.",
        "They found refuge in the warm cabin during the storm.",
      ],
      hints: ["Think of somewhere safe to hide", "A place of comfort and protection"],
      swapFrom: "safe place",
      sentenceTemplate: "The cabin was a safe place during the storm.",
      sentenceAnswer: "The cabin was a refuge during the storm.",
    },
    {
      word: "emerged",
      meaning: "Came out or appeared",
      impression: "Surprise, change",
      examples: [
        "A butterfly emerged from its cocoon, wings glistening.",
        "The truth finally emerged after months of investigation.",
      ],
      hints: ["Something appearing or coming out", "Often shows a revelation or transformation"],
      swapFrom: "came out or appeared",
      sentenceTemplate: "The butterfly came out or appeared from its cocoon.",
      sentenceAnswer: "The butterfly emerged from its cocoon.",
    },
    {
      word: "swarmed",
      meaning: "Moved in a large, busy group",
      impression: "Chaos, activity",
      examples: ["Tourists swarmed the beach on the sunny weekend.", "Bees swarmed around the fallen ice cream cone."],
      hints: ["Many moving together in a busy way", "Creates feeling of crowded chaos"],
      swapFrom: "moved in a big group",
      sentenceTemplate: "The tourists moved in a big group to the beach.",
      sentenceAnswer: "The tourists swarmed to the beach.",
    },
    {
      word: "sumptuous",
      meaning: "Rich, luxurious, and impressive",
      impression: "Pleasure, indulgence",
      examples: [
        "The sumptuous feast made everyone's mouth water.",
        "She admired the sumptuous velvet curtains in the theater.",
      ],
      hints: ["Describes something very fancy and expensive", "Makes you think of luxury and wealth"],
      swapFrom: "very fancy and rich",
      sentenceTemplate: "The food was very fancy and rich.",
      sentenceAnswer: "The food was sumptuous.",
    },
    {
      word: "jostling",
      meaning: "Bumping or pushing in a crowd",
      impression: "Tension, disorder",
      examples: [
        "The passengers were jostling for space on the crowded train.",
        "He felt the constant jostling of the busy market.",
      ],
      hints: ["Think of pushing and bumping in a crowd", "Creates a feeling of crowded chaos or tension"],
      swapFrom: "bumping or pushing",
      sentenceTemplate: "People were bumping or pushing in the crowded market.",
      sentenceAnswer: "People were jostling in the crowded market.",
    },
    {
      word: "devoured",
      meaning: "Ate greedily or hungrily",
      impression: "Hunger, desire",
      examples: [
        "The hungry child devoured the entire pizza.",
        "She devoured the book in a single sitting, eager for more.",
      ],
      hints: ["Think of eating very quickly and eagerly", "Shows strong hunger or intense consumption"],
      swapFrom: "ate quickly and hungrily",
      sentenceTemplate: "He ate quickly and hungrily after the long hike.",
      sentenceAnswer: "He devoured his meal after the long hike.",
    },
    {
      word: "held her mum's hand tightly",
      meaning: "Gripping hand with fear or anxiety",
      impression: "Nervousness, protection",
      examples: [
        "She held her mum's hand tightly as they crossed the busy street.",
        "The little boy held his mum's hand tightly during the scary movie.",
      ],
      hints: ["Shows fear or a need for comfort", "Indicates a strong bond or reliance"],
      swapFrom: "gripped her mum's hand with fear",
      sentenceTemplate: "She gripped her mum's hand with fear as they crossed the busy street.",
      sentenceAnswer: "She held her mum's hand tightly as they crossed the busy street.",
    },
    {
      word: "lungs getting tighter",
      meaning: "Finding it hard to breathe",
      impression: "Fear, anxiety",
      examples: [
        "His lungs getting tighter, he struggled to catch his breath.",
        "The sudden shock made her lungs getting tighter.",
      ],
      hints: ["Describes difficulty breathing due to stress or fear", "Creates a sense of panic or suffocation"],
      swapFrom: "finding it hard to breathe",
      sentenceTemplate: "He was finding it hard to breathe, he struggled to catch his breath.",
      sentenceAnswer: "His lungs getting tighter, he struggled to catch his breath.",
    },
    {
      word: "filled with cotton wool",
      meaning: "Feeling confused or distant",
      impression: "Disorientation, dullness",
      examples: [
        "After the long flight, her head felt filled with cotton wool.",
        "The news left him feeling as if his mind was filled with cotton wool.",
      ],
      hints: ["Describes a foggy or unclear mental state", "Suggests confusion or a lack of sharpness"],
      swapFrom: "feeling confused or distant",
      sentenceTemplate: "After the long flight, her head felt feeling confused or distant.",
      sentenceAnswer: "After the long flight, her head felt filled with cotton wool.",
    },
    {
      word: "greedy eyes",
      meaning: "Looking with intense desire",
      impression: "Desire, selfishness",
      examples: [
        "He looked at the cake with greedy eyes, wanting it all for himself.",
        "Her greedy eyes scanned the jewels in the display case.",
      ],
      hints: ["Shows strong desire, often for something material", "Suggests selfishness or covetousness"],
      swapFrom: "looking with intense desire",
      sentenceTemplate: "He looked at the cake looking with intense desire, wanting it all for himself.",
      sentenceAnswer: "He looked at the cake with greedy eyes, wanting it all for himself.",
    },
    {
      word: "mouth started to water",
      meaning: "Salivating in anticipation of food",
      impression: "Hunger, temptation",
      examples: [
        "The smell of freshly baked bread made his mouth start to water.",
        "Just thinking about the chocolate cake made her mouth start to water.",
      ],
      hints: ["Indicates strong hunger or craving for food", "Shows anticipation and desire"],
      swapFrom: "salivating in anticipation of food",
      sentenceTemplate: "The smell of freshly baked bread made his mouth salivating in anticipation of food.",
      sentenceAnswer: "The smell of freshly baked bread made his mouth start to water.",
    },
  ],
  character: [
    {
      word: "sinister",
      meaning: "Scary and suggesting something bad will happen",
      impression: "Evil character type",
      examples: [
        "A sinister smile crept across his face as he stepped into the shadows.",
        "The sinister figure watched from behind the tree.",
      ],
      hints: ["Describes someone who seems evil or threatening", "Creates fear and suspicion"],
      swapFrom: "scary and bad",
      sentenceTemplate: "The man had a scary and bad smile.",
      sentenceAnswer: "The man had a sinister smile.",
    },
    {
      word: "cruel",
      meaning: "Enjoying hurting or upsetting others",
      impression: "Mean character type",
      examples: [
        "The cruel bully laughed at the smaller child's tears.",
        "His cruel words left her feeling deeply hurt.",
      ],
      hints: ["Someone who enjoys causing pain or distress", "Deliberately unkind and hurtful"],
      swapFrom: "bad man who liked hurting people",
      sentenceTemplate: "He was a bad man who liked hurting people.",
      sentenceAnswer: "He was a cruel man.",
    },
    {
      word: "compassionate",
      meaning: "Showing care and concern for others",
      impression: "Kind character type",
      examples: [
        "The compassionate nurse held the patient's hand gently.",
        "Her compassionate nature made everyone feel welcomed.",
      ],
      hints: ["Someone who cares deeply about others", "Shows kindness and understanding"],
      swapFrom: "very nice and loving",
      sentenceTemplate: "The nurse was very nice and loving.",
      sentenceAnswer: "The nurse was compassionate.",
    },
    {
      word: "hostile",
      meaning: "Angry and unfriendly",
      impression: "Aggressive character type",
      examples: [
        "The hostile crowd shouted angrily at the speaker.",
        "His hostile attitude made everyone uncomfortable.",
      ],
      hints: ["Someone who is angry and unwelcoming", "Unfriendly and aggressive behavior"],
      swapFrom: "angry and unfriendly",
      sentenceTemplate: "The crowd was angry and unfriendly at the speaker.",
      sentenceAnswer: "The crowd was hostile at the speaker.",
    },
    {
      word: "malicious",
      meaning: "Intending to harm or hurt others",
      impression: "Evil character type",
      examples: [
        "His malicious grin revealed his cruel intentions.",
        "She spread malicious rumors to hurt her classmate.",
      ],
      hints: ["Someone who wants to cause harm on purpose", "Deliberately mean and hurtful"],
      swapFrom: "bad and mean",
      sentenceTemplate: "He was bad and mean.",
      sentenceAnswer: "He was malicious.",
    },
    {
      word: "snide",
      meaning: "Indirectly rude or insulting",
      impression: "Mean character type",
      examples: ["He made a snide remark about her new haircut.", "Her snide comments always left a bitter taste."],
      hints: ["Someone who makes subtly rude or mocking comments", "Sarcastic and unpleasant"],
      swapFrom: "rude and mocking way",
      sentenceTemplate: "He made a remark in a rude and mocking way about her new haircut.",
      sentenceAnswer: "He made a snide remark about her new haircut.",
    },
    {
      word: "gentle",
      meaning: "Soft, calm, and caring",
      impression: "Kind character type",
      examples: [
        "The gentle giant carefully picked up the injured bird.",
        "Her gentle voice calmed the frightened child.",
      ],
      hints: ["Someone who is soft and careful", "Never harsh or rough"],
      swapFrom: "nice and soft",
      sentenceTemplate: "The giant was nice and soft.",
      sentenceAnswer: "The giant was gentle.",
    },
    {
      word: "violent",
      meaning: "Using or involving physical force",
      impression: "Aggressive character type",
      examples: ["The violent storm ripped trees from the ground.", "He had a violent temper that scared everyone."],
      hints: ["Someone who uses physical force or aggression", "Can be destructive or explosive"],
      swapFrom: "scary and violent manner",
      sentenceTemplate: "The storm was in a scary and violent manner.",
      sentenceAnswer: "The storm was violent.",
    },
    {
      word: "menacing",
      meaning: "Threatening or frightening",
      impression: "Evil character type",
      examples: ["A menacing shadow loomed over the old house.", "His menacing stare made her shiver."],
      hints: ["Someone or something that seems threatening", "Creates a feeling of fear or danger"],
      swapFrom: "threatening or frightening",
      sentenceTemplate: "The shadow was threatening or frightening over the old house.",
      sentenceAnswer: "The menacing shadow loomed over the old house.",
    },
    {
      word: "nasty",
      meaning: "Mean, unpleasant, or unkind",
      impression: "Mean character type",
      examples: [
        "She received a nasty letter from an anonymous sender.",
        "The nasty smell filled the old abandoned house.",
      ],
      hints: ["Someone who is very unpleasant or unkind", "Can describe a bad smell or taste too"],
      swapFrom: "mean, unpleasant, or unkind",
      sentenceTemplate: "She received a mean, unpleasant, or unkind letter from an anonymous sender.",
      sentenceAnswer: "She received a nasty letter from an anonymous sender.",
    },
    {
      word: "warm-hearted",
      meaning: "Kind and loving",
      impression: "Kind character type",
      examples: [
        "The warm-hearted old woman always offered tea to her neighbors.",
        "His warm-hearted smile made everyone feel at ease.",
      ],
      hints: ["Someone who is genuinely kind and caring", "Shows affection and generosity"],
      swapFrom: "kind and loving",
      sentenceTemplate: "The old woman was kind and loving.",
      sentenceAnswer: "The old woman was warm-hearted.",
    },
    {
      word: "fierce",
      meaning: "Strong, angry, or powerful",
      impression: "Aggressive character type",
      examples: [
        "The fierce warrior defended the castle bravely.",
        "She gave him a fierce look that made him step back.",
      ],
      hints: ["Someone very intense and powerful", "Strong emotions, often anger or determination"],
      swapFrom: "very angry and strong",
      sentenceTemplate: "The warrior was very angry and strong.",
      sentenceAnswer: "The warrior was fierce.",
    },
  ],
}

export type Stage = 1 | 2 | 3 | 4 | 5
export type VocabType = "descriptive" | "character"

export interface VocabularyItem {
  word: string
  meaning: string
  impression: string
  examples: string[]
  hints?: string[] // Hints are optional now
  swapFrom?: string // New property for word swap stage
  sentenceTemplate?: string
  sentenceAnswer?: string
}
